baseURL = "https://arzg.github.io/"
languageCode = "en-uk"
title = "arzg’s website"

pygmentsUseClasses = true

[markup.goldmark.renderer]
unsafe = true

[minify.tdewolff.html]
keepWhitespace = false
