baseURL = "https://blog.lunaa.me/"
languageCode = "en-us"
title = "Luna’s Blog"

[markup.highlight]
noClasses = false

[markup.goldmark.renderer]
unsafe = true

[minify.tdewolff.html]
keepWhitespace = false
