baseURL = "https://lunacookies.github.io/"
languageCode = "en-uk"
title = "Luna’s Website"

# disable Hugo’s syntax highlighting since we use PrismJS instead
[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[minify.tdewolff.html]
keepWhitespace = false
