name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Format using Prettier
        run: |
          yarn global add prettier@2.2.1 prettier-plugin-go-template

          for file in $(find . \
            -name '*.html' \
            -or -name '*.js' \
            -or -name '*.md' \
            -or -name '*.scss' \
            -or -name '*.json' \
          ); do
            $(yarn global bin)/prettier --write $file &
          done

          wait

          if [[ -n "$(git status -s)" ]]; then
            git config --global user.email 'actions@github.com'
            git config --global user.name 'GitHub Action'
            git commit --all --message 'Prettified Code!'
            git push
          fi

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: latest
          extended: true

      - name: Install Yarn dependencies
        uses: borales/actions-yarn@v2.3.0

      - name: Build site with Hugo
        run: hugo --minify --buildFuture

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          publish_dir: ./public
          publish_branch: master
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: arzg/arzg.github.io
